kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-controller
  namespace: default
data:
  enable-opentelemetry: false
  http-snippet: "load_module /datadog_mount/ngx_http_datadog_module.so;"
