# Cancel redundant pipelines when new commits are pushed to the same branch.
workflow:
  auto_cancel:
    on_new_commit: interruptible

stages:
  - build-and-test-fast
  - build-all
  - test-all
  - benchmarks

default:
  interruptible: true

include:
  - local: ".gitlab/build-and-test-all-static.yml"
  - local: ".gitlab/build-and-test-all.yml"
  - local: ".gitlab/build-and-test-fast-static.yml"
  - local: ".gitlab/build-and-test-fast.yml"

macrobenchmarks:
  stage: benchmarks
  needs: []
  trigger:
    include: ".gitlab/benchmarks.yml"
  rules:
    - if: $NIGHTLY_BENCHMARKS || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /^release\/v/
      when: always
    - when: manual
      allow_failure: true
