version: '2'

services:
  openresty:
    stdin_open: true
    tty: true
    # image: openresty/openresty:1.21.4.1-3-alpine
    build:
      context: .
      dockerfile: crash.dockerfile
    ports:
      - '8080:80'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./crash.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./.docker-build/libngx_http_datadog_module.so:/usr/local/openresty/nginx/modules/ngx_http_datadog_module.so:ro
