# This file is generated by bin/generate_cmakelists.py

cmake_minimum_required(VERSION 3.12)

project(nginx_module)

add_library(nginx_module OBJECT)
set_property(TARGET nginx_module PROPERTY POSITION_INDEPENDENT_CODE ON)

target_sources(nginx_module
    PRIVATE
        nginx/objs/ngx_http_datadog_module_modules.c
)

include_directories(
    SYSTEM
        nginx/src/event
        nginx/src/http/modules
        nginx/src/http
        nginx/src/os/unix
        nginx/objs
        nginx/src/core
        nginx/src/event/modules
)

