    when:
      and:
        - not: << pipeline.git.tag >>
        - << pipeline.parameters.run-installer-workflow >>
    jobs:
     - build_installer_amd64:
        name: build installer on amd64
     - build_installer_arm64:
        name: build installer on arm64
     - installer_test:
        matrix:
          parameters:
            base-dockerfile:
            - 'bookworm.Dockerfile'
            - 'alpine.Dockerfile'
            - 'al2023.Dockerfile'
        name: test installer with << matrix.base-dockerfile >> base image
        requires:
        - build installer on amd64
        - build installer on arm64
     - installer_download_test:
        name: test installer download
