    when:
      or:
        - equal: [ release, << pipeline.parameters.action >> ]
        - matches: { pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+", value: << pipeline.git.tag >> }
    jobs:
    - build_openresty:
        filters:
          tags:
            only: /^v.*/
        matrix:
          parameters:
            arch:
            - amd64
            - arm64
            resty-version:
            - 1.27.1.2
            waf:
            - 'ON'
            - 'OFF'
        name: build openresty << matrix.resty-version >> on << matrix.arch >> WAF << matrix.waf >>
    - test-openresty:
        filters:
          tags:
            only: /^v.*/
        matrix:
          parameters:
            arch:
            - amd64
            - arm64
            waf:
            - 'ON'
            - 'OFF'
            base-image:
            - openresty/openresty:1.27.1.2-alpine
            resty-version:
            - 1.27.1.2
        name: test openresty << matrix.resty-version >> on << matrix.base-image >>:<< matrix.arch >> WAF << matrix.waf >>
        requires:
        - build openresty << matrix.resty-version >> on << matrix.arch >> WAF << matrix.waf >>
