# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache 2.0 License. This product includes software developed at
# Datadog (https://www.datadoghq.com/).
#
# Copyright 2024-Present Datadog, Inc.

services:
  envoy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT_WEB:-8080}:8080'
      - '${PORT_WEB:-8081}:8081'
    develop:
      watch:
        - action: sync+restart
          path: ./static
          target: /var/www
          ignore:
            - .git
            - .gitignore
            - .vscode
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: docker-compose.yml
        - action: rebuild
          path: envoy.yaml
        - action: rebuild
          path: ./lib/datadog_rum.lua
