blank_issues_enabled: false
contact_links:
  - name: Bug Report (High Priority)
    url: https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:apm&tf_1900004146284=pt_apm_language:proxy/c__
    about: Create an expedited bug report via the helpdesk (no login required). This enables us to look up your account and lets you share additional information privately.
  - name: Feature Request (High Priority)
    url: https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:apm&tf_1900004146284=pt_apm_language:proxy/c__&tf_1260825272270=pt_apm_category_feature_request
    about: Create an expedited feature request via the helpdesk (no login required). This helps us prioritize your request and lets you share additional information privately.
