name: Feature Request (Low Priority)
description: Create a public Feature Request. Note that these may not be addressed as quickly as the helpdesk and that looking up account information will be difficult.
title: "[FEATURE]: "
labels: feature-request
body:
  - type: textarea
    attributes:
      label: Feature Goal
      description: A clear and concise goal of what you want to achieve.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Problem
      description: If applicable, a clear and concise description of the problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Considered Alternatives
      description: A clear and concise description of any alternative solutions or features you considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other relevant context or screenshots.
    validations:
      required: false
