ARG TOOLCHAIN_IMAGE=nginx_musl_toolchain
FROM ${TOOLCHAIN_IMAGE}

ARG ARCH=aarch64
ARG NGINX_VERSION

RUN set -eux; \
    case "$ARCH" in \
      arm64) ARCH=aarch64 ;; \
      amd64) ARCH=x86_64 ;; \
    esac; \
    sysroot="/sysroot/${ARCH}-none-linux-musl"; \
    triple="${ARCH}-none-linux-musl"; \
    addgroup -S nginx; \
    adduser -S -D -H -h /var/cache/nginx -s /sbin/nologin -G nginx nginx; \
    mkdir -p /var/cache/nginx /var/log/nginx /run; \
    cd /tmp; \
    wget -q "https://www.openssl.org/source/openssl-3.5.5.tar.gz"; \
    tar -xzf "openssl-3.5.5.tar.gz"; \
    wget -q "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz"; \
    tar -xzf "nginx-${NGINX_VERSION}.tar.gz"; \
    cc_opt="--target=${triple} --sysroot=${sysroot} -fno-omit-frame-pointer -O1 -g -fsanitize=address -DNGX_COMPAT=1 -Wno-error=sign-compare"; \
    ld_opt="--target=${triple} --sysroot=${sysroot} -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -resource-dir ${sysroot}/usr/lib/resource_dir -fsanitize=address -shared-libasan -Wl,-rpath,/usr/lib/llvm17/lib/clang/17/lib/linux -Wl,-rpath,/usr/lib"; \
    case "$ARCH" in \
      x86_64)  ossl_target="linux-x86_64-clang" ;; \
      aarch64) ossl_target="linux-aarch64" ;; \
      *)       ossl_target="linux-${ARCH}" ;; \
    esac; \
    cd "/tmp/openssl-3.5.5"; \
    CC=clang-17 ./Configure "$ossl_target" \
      --prefix="${sysroot}/usr" \
      no-shared no-threads no-tests \
      --target=${triple} --sysroot=${sysroot} \
      -fno-omit-frame-pointer -O1 -g -fsanitize=address \
      -fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind \
      -resource-dir ${sysroot}/usr/lib/resource_dir; \
    make -j"$(nproc)"; \
    make install_sw LIBDIR=lib; \
    rm -f "${sysroot}/usr/lib/libssl.so" "${sysroot}/usr/lib/libcrypto.so"; \
    cd "/tmp/nginx-${NGINX_VERSION}"; \
    ./configure \
      --prefix=/etc/nginx \
      --sbin-path=/usr/sbin/nginx \
      --modules-path=/usr/lib/nginx/modules \
      --conf-path=/etc/nginx/nginx.conf \
      --error-log-path=/var/log/nginx/error.log \
      --http-log-path=/var/log/nginx/access.log \
      --pid-path=/run/nginx.pid \
      --lock-path=/var/run/nginx.lock \
      --http-client-body-temp-path=/var/cache/nginx/client_temp \
      --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
      --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
      --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
      --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
      --user=nginx \
      --group=nginx \
      --with-compat \
      --with-file-aio \
      --with-threads \
      --with-http_auth_request_module \
      --with-http_ssl_module \
      --with-http_v2_module \
      --with-http_v3_module \
      --with-http_stub_status_module \
      --with-http_realip_module \
      --with-http_gzip_static_module \
      --with-http_sub_module \
      --with-cc=clang-17 \
      --with-cc-opt="$cc_opt" \
      --with-ld-opt="$ld_opt"; \
    make -j"$(nproc)"; \
    make install; \
    rm -rf "/tmp/nginx-${NGINX_VERSION}" "/tmp/nginx-${NGINX_VERSION}.tar.gz" "/tmp/openssl-3.5.5" "/tmp/openssl-3.5.5.tar.gz"

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
