# check=skip=InvalidDefaultArgInFrom
ARG TOOLCHAIN_IMAGE
FROM ${TOOLCHAIN_IMAGE}

ARG ARCH=aarch64
ARG NGINX_VERSION

ENV MUSL_CLANG_SANITIZE=address,undefined

COPY ngx_http_copy_filter_ubsan.patch ngx_http_huff_encode_ubsan.patch /tmp/

RUN set -eux; \
    addgroup -S nginx; \
    adduser -S -D -H -h /var/cache/nginx -s /sbin/nologin -G nginx nginx; \
    mkdir -p /var/cache/nginx /var/log/nginx /run; \
    cd /tmp; \
    wget -q "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz"; \
    tar -xzf "nginx-${NGINX_VERSION}.tar.gz"; \
    cc_opt="-O1 -g -fsanitize=address,undefined -DNGX_COMPAT=1"; \
    cc_opt="$cc_opt -DNGX_HAVE_NONALIGNED=0 -Wno-error=sign-compare"; \
    ld_opt="-fsanitize=address,undefined,vptr"; \
    ld_opt="$ld_opt -fsanitize-link-c++-runtime"; \
    ld_opt="$ld_opt -Wl,-Bdynamic"; \
    cd "/tmp/nginx-${NGINX_VERSION}"; \
    patch -p1 < /tmp/ngx_http_copy_filter_ubsan.patch; \
    patch -p1 < /tmp/ngx_http_huff_encode_ubsan.patch; \
    ./configure \
      --prefix=/etc/nginx \
      --sbin-path=/usr/sbin/nginx \
      --modules-path=/usr/lib/nginx/modules \
      --conf-path=/etc/nginx/nginx.conf \
      --error-log-path=/var/log/nginx/error.log \
      --http-log-path=/var/log/nginx/access.log \
      --pid-path=/run/nginx.pid \
      --lock-path=/var/run/nginx.lock \
      --http-client-body-temp-path=/var/cache/nginx/client_temp \
      --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
      --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
      --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
      --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
      --user=nginx \
      --group=nginx \
      --with-compat \
      --with-file-aio \
      --with-threads \
      --with-http_auth_request_module \
      --with-http_ssl_module \
      --with-http_v2_module \
      --with-http_v3_module \
      --with-http_stub_status_module \
      --with-http_realip_module \
      --with-http_gzip_static_module \
      --with-http_sub_module \
      --with-cc=musl-clang \
      --with-cc-opt="$cc_opt" \
      --with-ld-opt="$ld_opt"; \
    make -j"$(nproc)"; \
    make install; \
    rm -rf "/tmp/nginx-${NGINX_VERSION}" \
      "/tmp/nginx-${NGINX_VERSION}.tar.gz" \
      /tmp/ngx_http_copy_filter_ubsan.patch \
      /tmp/ngx_http_huff_encode_ubsan.patch

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV ASAN_OPTIONS=halt_on_error=1:detect_leaks=0
ENV UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1
