[package]
name = "check_conf"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
inject-browser-sdk = { path = "../../lib/inject-browser-sdk" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

