name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - "**"

jobs:
  update-rules:
    runs-on: ubuntu-latest
    permissions:
      actions: read # read secrets
      contents: write # Creates a branch
      pull-requests: write # Creates a PR
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'DataDog/appsec-event-rules'
